# Render deployment configuration for Secure File Vault
# This file deploys the entire application: PostgreSQL database, backend API, and frontend

services:
  # Backend API Service
  - type: web
    name: secure-file-vault-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: secure-file-vault-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: GIN_MODE
        value: release
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: RATE_LIMIT_RPS
        value: "100"
      - key: DEFAULT_QUOTA_MB
        value: "1000"
      - key: MAX_FILE_SIZE_MB
        value: "100"
    disk:
      name: backend-uploads-disk
      mountPath: /app/uploads
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Web Service
  - type: web
    name: secure-file-vault-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    region: oregon
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: secure-file-vault-backend
          property: host
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

# PostgreSQL Database
databases:
  - name: secure-file-vault-db
    plan: free
    region: oregon
    databaseName: filevault
    user: filevault
    autoDeploy: true
